/** @brief 已解析设计令牌的只读映射 (Readonly map of resolved design tokens). */
// biome-ignore format: 生成文件保持构建器的确定性输出 (Generated file keeps deterministic builder output).
export const tokens = {
  "color.cream-50": "#fffdf8",
  "color.cream-100": "#fffaf2",
  "color.cream-200": "#fff6ea",
  "color.cream-300": "#fff1e2",
  "color.cream-400": "#ffe4c3",
  "color.brown-100": "#d9b8a6",
  "color.brown-300": "#805648",
  "color.brown-500": "#4b2a1e",
  "color.brown-700": "#30201b",
  "color.brown-800": "#21130f",
  "color.brown-900": "#19100e",
  "color.ink": "#26110b",
  "color.coral-300": "#ffb18c",
  "color.coral-400": "#ff8569",
  "color.coral-500": "#f27a50",
  "color.coral-600": "#e66a3f",
  "color.coral-700": "#bd4525",
  "color.gold": "#ffb55e",
  "color.green": "#4daf76",
  "color.red": "#d65345",
  "color.gray": "#9c8d86",
  "font.family.sans": "\"Atkinson Hyperlegible\", \"Noto Sans SC\", \"PingFang SC\", \"Microsoft YaHei\", system-ui, sans-serif",
  "font.family.display": "Georgia, \"Noto Serif SC\", serif",
  "font.family.mono": "\"IBM Plex Mono\", \"Cascadia Mono\", SFMono-Regular, monospace",
  "font.size.xs": "12px",
  "font.size.sm": "14px",
  "font.size.md": "16px",
  "font.size.lg": "20px",
  "font.size.xl": "28px",
  "font.size.2xl": "40px",
  "space.0": "0px",
  "space.1": "4px",
  "space.2": "8px",
  "space.3": "12px",
  "space.4": "16px",
  "space.5": "24px",
  "space.6": "32px",
  "space.7": "48px",
  "space.8": "64px",
  "space.xs": "4px",
  "space.sm": "8px",
  "space.md": "12px",
  "space.lg": "16px",
  "space.xl": "24px",
  "space.2xl": "32px",
  "radius.sm": "10px",
  "radius.md": "18px",
  "radius.lg": "26px",
  "radius.pill": "999px",
  "shadow.sm": "0px 8px 18px 0px #9e4e251a",
  "shadow.md": "0px 16px 34px 0px #9e4e2529",
  "shadow.dark-sm": "0px 8px 18px 0px #00000038",
  "shadow.dark-md": "0px 16px 34px 0px #00000061",
  "motion.fast": "160ms",
  "motion.base": "220ms",
  "motion.slow": "420ms",
  "motion.ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  "motion.ease-emphasized": "cubic-bezier(0.2, 0.8, 0.2, 1)",
  "layout.content": "1180px",
  "layout.reading": "720px",
  "semantic.light.background": "#fff6ea",
  "semantic.light.background-end": "#fff1e2",
  "semantic.light.surface": "#fffbf4eb",
  "semantic.light.surface-strong": "#fffdf8",
  "semantic.light.surface-muted": "#fff1dd",
  "semantic.light.text": "#4b2a1e",
  "semantic.light.text-soft": "#805648",
  "semantic.light.heading": "#26110b",
  "semantic.light.accent": "#e66a3f",
  "semantic.light.accent-strong": "#bd4525",
  "semantic.light.accent-wash": "#ffe1cccc",
  "semantic.light.on-accent": "#fffaf2",
  "semantic.light.border": "#f3bf98bd",
  "semantic.light.focus": "#542516",
  "semantic.light.success": "#4daf76",
  "semantic.light.danger": "#d65345",
  "semantic.light.neutral": "#9c8d86",
  "semantic.dark.background": "#21130f",
  "semantic.dark.background-end": "#19100e",
  "semantic.dark.surface": "#2f1c17f0",
  "semantic.dark.surface-strong": "#30201b",
  "semantic.dark.surface-muted": "#3c241d",
  "semantic.dark.text": "#f6e7dc",
  "semantic.dark.text-soft": "#d9b8a6",
  "semantic.dark.heading": "#fff6ef",
  "semantic.dark.accent": "#f27a50",
  "semantic.dark.accent-strong": "#ffb18c",
  "semantic.dark.accent-wash": "#853e2a6b",
  "semantic.dark.on-accent": "#2b1711",
  "semantic.dark.border": "#a06345b3",
  "semantic.dark.focus": "#ffe0a3",
  "semantic.dark.success": "#4daf76",
  "semantic.dark.danger": "#d65345",
  "semantic.dark.neutral": "#9c8d86"
} as const;

/** @brief 所有可用设计令牌名称 (All available design-token names). */
export const tokenNames = Object.freeze(Object.keys(tokens)) as readonly (keyof typeof tokens)[];

/** @brief 有效设计令牌名称联合类型 (Union of valid design-token names). */
export type TokenName = keyof typeof tokens;
